import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    fontSize: {
      xs: ["11px", { lineHeight: "16px" }],
      sm: ["13px", { lineHeight: "20px" }],
      base: ["15px", { lineHeight: "24px" }],
      lg: ["18px", { lineHeight: "28px" }],
      xl: ["22px", { lineHeight: "30px" }],
      "2xl": ["28px", { lineHeight: "36px" }],
      "3xl": ["36px", { lineHeight: "44px" }],
      "5xl": ["56px", { lineHeight: "64px" }],
    },
    extend: {
      colors: {
        white: {
          0: "rgb(var(--white-0) / <alpha-value>)",
          50: "rgb(var(--white-50) / <alpha-value>)",
          100: "rgb(var(--white-100) / <alpha-value>)",
          200: "rgb(var(--white-200) / <alpha-value>)",
          300: "rgb(var(--white-300) / <alpha-value>)",
          400: "rgb(var(--white-400) / <alpha-value>)",
          500: "rgb(var(--white-500) / <alpha-value>)",
          600: "rgb(var(--white-600) / <alpha-value>)",
          700: "rgb(var(--white-700) / <alpha-value>)",
          800: "rgb(var(--white-800) / <alpha-value>)",
          900: "rgb(var(--white-900) / <alpha-value>)",
          1000: "rgb(var(--white-1000) / <alpha-value>)",
        },
        ink: {
          0: "rgb(var(--ink-0) / <alpha-value>)",
          50: "rgb(var(--ink-50) / <alpha-value>)",
          100: "rgb(var(--ink-100) / <alpha-value>)",
          200: "rgb(var(--ink-200) / <alpha-value>)",
          300: "rgb(var(--ink-300) / <alpha-value>)",
          400: "rgb(var(--ink-400) / <alpha-value>)",
          500: "rgb(var(--ink-500) / <alpha-value>)",
          600: "rgb(var(--ink-600) / <alpha-value>)",
          700: "rgb(var(--ink-700) / <alpha-value>)",
          800: "rgb(var(--ink-800) / <alpha-value>)",
          900: "rgb(var(--ink-900) / <alpha-value>)",
          1000: "rgb(var(--ink-1000) / <alpha-value>)",
          DEFAULT: "rgb(var(--color-ink) / <alpha-value>)",
        },
        paper: {
          0: "rgb(var(--paper-0) / <alpha-value>)",
          50: "rgb(var(--paper-50) / <alpha-value>)",
          100: "rgb(var(--paper-100) / <alpha-value>)",
          200: "rgb(var(--paper-200) / <alpha-value>)",
          300: "rgb(var(--paper-300) / <alpha-value>)",
          400: "rgb(var(--paper-400) / <alpha-value>)",
          500: "rgb(var(--paper-500) / <alpha-value>)",
          600: "rgb(var(--paper-600) / <alpha-value>)",
          700: "rgb(var(--paper-700) / <alpha-value>)",
          800: "rgb(var(--paper-800) / <alpha-value>)",
          900: "rgb(var(--paper-900) / <alpha-value>)",
          1000: "rgb(var(--paper-1000) / <alpha-value>)",
          DEFAULT: "rgb(var(--color-paper) / <alpha-value>)",
          dark: "rgb(var(--color-paper-dark) / <alpha-value>)",
        },
        sage: {
          0: "rgb(var(--sage-0) / <alpha-value>)",
          50: "rgb(var(--sage-50) / <alpha-value>)",
          100: "rgb(var(--sage-100) / <alpha-value>)",
          200: "rgb(var(--sage-200) / <alpha-value>)",
          300: "rgb(var(--sage-300) / <alpha-value>)",
          400: "rgb(var(--sage-400) / <alpha-value>)",
          500: "rgb(var(--sage-500) / <alpha-value>)",
          600: "rgb(var(--sage-600) / <alpha-value>)",
          700: "rgb(var(--sage-700) / <alpha-value>)",
          800: "rgb(var(--sage-800) / <alpha-value>)",
          900: "rgb(var(--sage-900) / <alpha-value>)",
          1000: "rgb(var(--sage-1000) / <alpha-value>)",
          DEFAULT: "rgb(var(--color-sage) / <alpha-value>)",
          dark: "rgb(var(--color-sage-dark) / <alpha-value>)",
          light: "rgb(var(--color-sage-light) / <alpha-value>)",
        },
        terracotta: {
          0: "rgb(var(--terracotta-0) / <alpha-value>)",
          50: "rgb(var(--terracotta-50) / <alpha-value>)",
          100: "rgb(var(--terracotta-100) / <alpha-value>)",
          200: "rgb(var(--terracotta-200) / <alpha-value>)",
          300: "rgb(var(--terracotta-300) / <alpha-value>)",
          400: "rgb(var(--terracotta-400) / <alpha-value>)",
          500: "rgb(var(--terracotta-500) / <alpha-value>)",
          600: "rgb(var(--terracotta-600) / <alpha-value>)",
          700: "rgb(var(--terracotta-700) / <alpha-value>)",
          800: "rgb(var(--terracotta-800) / <alpha-value>)",
          900: "rgb(var(--terracotta-900) / <alpha-value>)",
          1000: "rgb(var(--terracotta-1000) / <alpha-value>)",
          DEFAULT: "rgb(var(--color-terracotta) / <alpha-value>)",
          light: "rgb(var(--color-terracotta-light) / <alpha-value>)",
        },
        gold: {
          0: "rgb(var(--gold-0) / <alpha-value>)",
          50: "rgb(var(--gold-50) / <alpha-value>)",
          100: "rgb(var(--gold-100) / <alpha-value>)",
          200: "rgb(var(--gold-200) / <alpha-value>)",
          300: "rgb(var(--gold-300) / <alpha-value>)",
          400: "rgb(var(--gold-400) / <alpha-value>)",
          500: "rgb(var(--gold-500) / <alpha-value>)",
          600: "rgb(var(--gold-600) / <alpha-value>)",
          700: "rgb(var(--gold-700) / <alpha-value>)",
          800: "rgb(var(--gold-800) / <alpha-value>)",
          900: "rgb(var(--gold-900) / <alpha-value>)",
          1000: "rgb(var(--gold-1000) / <alpha-value>)",
          DEFAULT: "rgb(var(--color-gold) / <alpha-value>)",
          light: "rgb(var(--color-gold-light) / <alpha-value>)",
        },
        slate: {
          0: "rgb(var(--slate-0) / <alpha-value>)",
          50: "rgb(var(--slate-50) / <alpha-value>)",
          100: "rgb(var(--slate-100) / <alpha-value>)",
          200: "rgb(var(--slate-200) / <alpha-value>)",
          300: "rgb(var(--slate-300) / <alpha-value>)",
          400: "rgb(var(--slate-400) / <alpha-value>)",
          500: "rgb(var(--slate-500) / <alpha-value>)",
          600: "rgb(var(--slate-600) / <alpha-value>)",
          700: "rgb(var(--slate-700) / <alpha-value>)",
          800: "rgb(var(--slate-800) / <alpha-value>)",
          900: "rgb(var(--slate-900) / <alpha-value>)",
          1000: "rgb(var(--slate-1000) / <alpha-value>)",
          DEFAULT: "rgb(var(--color-slate) / <alpha-value>)",
          light: "rgb(var(--color-slate-light) / <alpha-value>)",
        },
      },
      fontFamily: {
        display: ["var(--font-playfair-display)", "serif"],
        editorial: ["var(--font-crimson-pro)", "serif"],
        mono: ["var(--font-dm-mono)", "monospace"],
      },
      borderWidth: {
        "0.5": "0.5px",
      },
      transitionDuration: {
        "150": "150ms",
        "200": "200ms",
        "300": "300ms",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
